CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(100) NOT NULL,
  username VARCHAR(100),
  target_type VARCHAR(100),
  target_id VARCHAR(100),
  detail VARCHAR(1000),
  before_value VARCHAR(4000),
  after_value VARCHAR(4000),
  created_at TIMESTAMP NOT NULL
);
