DROP TABLE IF EXISTS todo_groups;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(20) NOT NULL
);

CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author VARCHAR(50) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  due_date DATE,
  priority VARCHAR(10) NOT NULL,
  status VARCHAR(20),
  deleted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  version BIGINT,
  user_id BIGINT NOT NULL,
  category_id BIGINT
);

CREATE TABLE todo_groups (
  todo_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  PRIMARY KEY (todo_id, group_id)
);
